version: "3.9"

services:
  django-app:
    build:
      context: .
      target: development
    container_name: django-app-dev
    ports:
      - "8000:8000"
    env_file:
      - ./project/.env
    environment:
      DJANGO_SETTINGS_MODULE: project.settings.dev
    volumes:
      - ./project:/app/project
      - ./project/requirements.txt:/app/requirements.txt
      - static_volume:/app/project/staticfiles
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres-db-dev
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/project/staticfiles:ro
    depends_on:
      - django-app
    restart: unless-stopped

volumes:
  postgres_data_dev:
  static_volume: